#pragma once
#include <Eigen/Dense>
#include <Eigen/Sparse>
#include <algorithm>
#include <deque>
#include <iostream>
#include <memory>
#include <numeric>
#include <queue>
#include <random>
#include <string>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <vector>

#include "boost.hpp"
#include "cassert"
